# -*- coding: utf-8 -*-
"""data_curation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GtRAEQnt-AzTuWZMkwri1owyl4dcqGop
"""

"""
The pipeline has a few key components:
- **Heuristic pre-filters**: Language ID, length filters, MinHash dedup, n-gram repetition, perplexity outliers, toxicity - the standard stuff to remove obvious garbage before spending
GPU cycles
- **SeqlO-style dynamic mixtures**:
Deterministic, resumable sampling that maintains your target ratios (40% CC, 20% code, etc) regardless of total token budget - critical for proxy runs where you're not training on 6.7T tokens
- **Model-based quality scoring**: This is where it gets interesting
"""

"""
Why Deduplication Matters
Problem: Web crawl data (CommonCrawl) contains massive duplication
  - Same article scraped from 1000 mirror sites
  - Boilerplate text (cookie notices, navigation menus)
  - Near-duplicate versions of same document

Effects of training on duplicate data:
  - Model memorizes exact text instead of generalizing
  - Inflated benchmark scores (test set contamination)
  - Wasted compute training on redundant information

Scale: CommonCrawl → after dedup, 30-50% of data often removed
"""

"""### Detailed Explanation: Model-based Quality Scoring

In modern LLM pretraining (like Llama 3 or Gopher), simple heuristics (length, symbol ratio) aren't enough. We use **Model-based Scoring**:

1.  **The Oracle**: We define a 'gold standard' dataset (e.g., Wikipedia, StackOverflow, select textbooks).
2.  **The Classifier**: We train a small, fast model (like fastText or a DistilBERT) to distinguish 'Gold' data from 'Raw' web crawl data.
3.  **Inference**: We run this model over the entire TB-scale dataset. Every document gets a score from 0.0 to 1.0.
4.  **Thresholding**: We only keep documents with a score $> T$. This drastically increases the 'knowledge density' of the pretraining data, allowing smaller models to outperform larger ones trained on 'noisy' data.
"""

import re
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression

# 1. Simulate 'Gold' vs 'Noise' data for training our scorer
gold_data = [
    "The mathematical constant pi is a real number defined as the ratio of a circle's circumference.",
    "Photosynthesis is a process used by plants and other organisms to convert light energy into chemical energy.",
    "In computer science, a search algorithm is any algorithm which solves the search problem."
]
noise_data = [
    "CLICK HERE TO WIN A PRIZE!!! FREE DISCOUNT NOW BUY TODAY",
    "asdf jkl; 123456 !!! ??? test test test",
    "Privacy Policy Cookie Settings Contact Us About Us Careers"
]

# 2. Simple 'Model-based' Classifier (TF-IDF + Logistic Regression)
vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(gold_data + noise_data)
y = [1]*3 + [0]*3 # 1 for High Quality, 0 for Low Quality

quality_scorer = LogisticRegression().fit(X, y)

def get_quality_score(text):
    vec = vectorizer.transform([text])
    return quality_scorer.predict_proba(vec)[0][1] # Probability of being 'High Quality'

# Test it on Shakespeare
sample_doc = cleaned_docs[0]
score = get_quality_score(sample_doc)
print(f"Quality Score for Sample: {score:.4f}")

import random
import os
import urllib.request
from pathlib import Path

class Config:
  # Using the raw text version from a reliable mirror or Hugging Face source
  TINY_SHAKESPEARE_URL = "https://huggingface.co/datasets/roneneldan/TinyStories/resolve/main/TinyStoriesV2-GPT4-train.txt"
  data_dir = "./data"

cfg = Config()

def download_tinystories(data_dir: str = "./data") -> str:
    os.makedirs(data_dir, exist_ok=True)
    dst = os.path.join(data_dir, "tinystories.txt")
    if not os.path.exists(dst):
        print(f" Downloading TinyStories -> {dst}")
        urllib.request.urlretrieve(cfg.TINY_SHAKESPEARE_URL, dst)
        print("Done")
    return dst

def prepare_data():
  path = download_tinystories(cfg.data_dir)
  text = Path(path).read_text(encoding="utf-8")
  print(f" Corpus: {len(text):,} characters")
  return text

def heuristic_quality_filter(text_list):
    """Example filters used in pretraining (e.g., Gopher, LLaMA)."""
    filtered_docs = []
    for doc in text_list:
        # 1. Length filter (too short is often noise)
        if len(doc) < 100: continue

        # 2. Symbol-to-word ratio (prevents garbage/code-heavy snippets in natural language)
        words = doc.split()
        symbol_count = sum(1 for char in doc if not char.isalnum() and not char.isspace())
        if symbol_count / len(doc) > 0.1: continue

        filtered_docs.append(doc)
    return filtered_docs

# 1. Load and split the corpus into documents
corpus_text = prepare_data()
docs = [p.strip() for p in corpus_text.split('<|endoftext|>') if len(p.strip()) > 50]
print(f" Created {len(docs)} documents from TinyStories.")

cleaned_docs = heuristic_quality_filter(docs)
print(f"Docs remaining after quality filters: {len(cleaned_docs)}/{len(docs)}")

class DynamicMixtureSampler:
    def __init__(self, datasets, target_ratios):
        """
        datasets: Dict of {name: list_of_docs}
        target_ratios: Dict of {name: probability}
        """
        self.datasets = datasets
        self.names = list(target_ratios.keys())
        self.weights = list(target_ratios.values())

    def sample(self, total_tokens_needed):
        mixture = []
        # In a real pipeline (SeqIO), this is deterministic and resumable
        while len(mixture) < total_tokens_needed:
            # Pick a dataset based on weights
            source = random.choices(self.names, weights=self.weights)[0]
            doc = random.choice(self.datasets[source])
            mixture.append(doc)
        return mixture

# Example usage
data_sources = {
    "web_crawl": cleaned_docs, # Using our Shakespeare as 'web'
    "code_snippets": ["def add(a, b): return a + b", "class Model(nn.Module): pass"]
}

sampler = DynamicMixtureSampler(data_sources, target_ratios={"web_crawl": 0.7, "code_snippets": 0.3})
batch = sampler.sample(total_tokens_needed=5)

print(f"Generated a mixture batch of {len(batch)} documents.")
print(f"Sample from batch: {batch[0][:50]}...")

import os
import math
import urllib.request
from pathlib import Path
from typing import Iterator, List, Tuple
import numpy as np
from collections import defaultdict
from itertools import combinations

def download_tinystories(data_dir: str = "./data") -> str:
    os.makedirs(data_dir, exist_ok=True)
    dst = os.path.join(data_dir, "tinystories.txt")
    if not os.path.exists(dst):
        print(f" Downloading TinyStories -> {dst}")
        urllib.request.urlretrieve(cfg.TINY_SHAKESPEARE_URL, dst)
        print("Done")
    return dst

def prepare_data():
  path = download_tinystories(cfg.data_dir)
  text = Path(path).read_text(encoding="utf-8")
  print(f" Corpus: {len(text):,} characters")
  return text

# MinHash LSH Pipeline
class MinHashDeduplicator:
    def __init__(self, num_hashes=128, ngram_size=5, threshold=0.85):
        self.num_hashes = num_hashes
        self.ngram_size = ngram_size
        self.threshold  = threshold

        # Random hash functions: h(x) = (ax + b) mod p
        self.a = np.random.randint(1, 2**32, size=num_hashes)
        self.b = np.random.randint(0, 2**32, size=num_hashes)
        self.p = 2**31 - 1  # large prime

    def compute_minhash(self, text: str) -> np.ndarray:
        """Compute MinHash signature for a document."""
        # Generate n-grams (character-level)
        tokens = text.lower().split()
        ngrams = set()
        for i in range(len(tokens) - self.ngram_size + 1):
            ngrams.add(tuple(tokens[i:i+self.ngram_size]))

        # For each hash function, find minimum hash value across all n-grams
        signature = np.full(self.num_hashes, np.inf)
        for ngram in ngrams:
            ngram_hash = hash(ngram) & 0xFFFFFFFF  # 32-bit hash
            hashed = (self.a * ngram_hash + self.b) % self.p
            signature = np.minimum(signature, hashed)

        return signature.astype(np.uint32)

    def jaccard_from_signatures(self, sig1: np.ndarray, sig2: np.ndarray) -> float:
        """Estimate Jaccard similarity from MinHash signatures."""
        return float((sig1 == sig2).mean())

    def build_lsh_buckets(self, signatures: np.ndarray, n_bands: int = 16):
        """LSH: group documents likely to be near-duplicates into same bucket."""
        n_docs, n_hashes = signatures.shape
        rows_per_band = n_hashes // n_bands

        buckets = defaultdict(list)
        for doc_id in range(n_docs):
            for band in range(n_bands):
                start = band * rows_per_band
                end   = start + rows_per_band
                band_sig = tuple(signatures[doc_id, start:end])
                bucket_key = hash((band, band_sig))
                buckets[bucket_key].append(doc_id)

        return buckets

    def find_duplicates(self, documents: List[str]) -> List[Tuple[int, int]]:
        """Find all near-duplicate pairs."""
        signatures = np.array([self.compute_minhash(d) for d in documents])
        buckets = self.build_lsh_buckets(signatures)

        duplicate_pairs = set()
        for bucket_docs in buckets.values():
            if len(bucket_docs) < 2:
                continue
            # Verify pairs in same bucket
            for i, j in combinations(bucket_docs, 2):
                sim = self.jaccard_from_signatures(signatures[i], signatures[j])
                if sim >= self.threshold:
                    duplicate_pairs.add((min(i,j), max(i,j)))

        return list(duplicate_pairs)

class Config:
  # Using the raw text version from a reliable mirror or Hugging Face source
  TINY_SHAKESPEARE_URL = "https://huggingface.co/datasets/roneneldan/TinyStories/resolve/main/TinyStoriesV2-GPT4-train.txt"
  data_dir = "./data"

cfg = Config()

import numpy as np
from collections import defaultdict
from typing import List, Tuple
from itertools import combinations

import os
import urllib.request
from pathlib import Path
import numpy as np
from collections import defaultdict
from typing import List, Tuple
from itertools import combinations

class Config:
  # Using the raw text version from a reliable mirror or Hugging Face source
  TINY_SHAKESPEARE_URL = "https://huggingface.co/datasets/roneneldan/TinyStories/resolve/main/TinyStoriesV2-GPT4-train.txt"
  data_dir = "./data"

cfg = Config()

def download_tinystories(data_dir: str = "./data") -> str:
    os.makedirs(data_dir, exist_ok=True)
    dst = os.path.join(data_dir, "tinystories.txt")
    if not os.path.exists(dst):
        print(f" Downloading TinyStories -> {dst}")
        urllib.request.urlretrieve(cfg.TINY_SHAKESPEARE_URL, dst)
        print("Done")
    return dst

def prepare_data():
  path = download_tinystories(cfg.data_dir)
  text = Path(path).read_text(encoding="utf-8")
  print(f" Corpus: {len(text):,} characters")
  return text

# MinHash LSH Pipeline
class MinHashDeduplicator:
    def __init__(self, num_hashes=128, ngram_size=5, threshold=0.85):
        self.num_hashes = num_hashes
        self.ngram_size = ngram_size
        self.threshold  = threshold

        # Random hash functions: h(x) = (ax + b) mod p
        self.a = np.random.randint(1, 2**32, size=num_hashes)
        self.b = np.random.randint(0, 2**32, size=num_hashes)
        self.p = 2**31 - 1  # large prime

    def compute_minhash(self, text: str) -> np.ndarray:
        """Compute MinHash signature for a document."""
        # Generate n-grams (character-level)
        tokens = text.lower().split()
        ngrams = set()
        for i in range(len(tokens) - self.ngram_size + 1):
            ngrams.add(tuple(tokens[i:i+self.ngram_size]))

        # For each hash function, find minimum hash value across all n-grams
        signature = np.full(self.num_hashes, np.inf)
        for ngram in ngrams:
            ngram_hash = hash(ngram) & 0xFFFFFFFF  # 32-bit hash
            hashed = (self.a * ngram_hash + self.b) % self.p
            signature = np.minimum(signature, hashed)

        return signature.astype(np.uint32)

    def jaccard_from_signatures(self, sig1: np.ndarray, sig2: np.ndarray) -> float:
        """Estimate Jaccard similarity from MinHash signatures."""
        return float((sig1 == sig2).mean())

    def build_lsh_buckets(self, signatures: np.ndarray, n_bands: int = 16):
        """LSH: group documents likely to be near-duplicates into same bucket."""
        n_docs, n_hashes = signatures.shape
        rows_per_band = n_hashes // n_bands

        buckets = defaultdict(list)
        for doc_id in range(n_docs):
            for band in range(n_bands):
                start = band * rows_per_band
                end   = start + rows_per_band
                band_sig = tuple(signatures[doc_id, start:end])
                bucket_key = hash((band, band_sig))
                buckets[bucket_key].append(doc_id)

        return buckets

    def find_duplicates(self, documents: List[str]) -> List[Tuple[int, int]]:
        """Find all near-duplicate pairs."""
        signatures = np.array([self.compute_minhash(d) for d in documents])
        buckets = self.build_lsh_buckets(signatures)

        duplicate_pairs = set()
        for bucket_docs in buckets.values():
            if len(bucket_docs) < 2:
                continue
            # Verify pairs in same bucket
            for i, j in combinations(bucket_docs, 2):
                sim = self.jaccard_from_signatures(signatures[i], signatures[j])
                if sim >= self.threshold:
                    duplicate_pairs.add((min(i,j), max(i,j)))

        return list(duplicate_pairs)

# 1. Load and split the corpus into documents
corpus_text = prepare_data()
docs = [p.strip() for p in corpus_text.split('<|endoftext|>') if len(p.strip()) > 50]
print(f" Created {len(docs)} documents from TinyStories.")

# 2. Re-run deduplication demo on a sample to keep it fast
dedup = MinHashDeduplicator(num_hashes=128, threshold=0.8)
sample_size = 500
duplicate_pairs = dedup.find_duplicates(docs[:sample_size])

print(f" Found {len(duplicate_pairs)} near-duplicate pairs in the first {sample_size} stories.")

"""### Scaling the Deduplication Pipeline

For massive datasets (TB scale), we use these strategies:
1. **LSH Bucketing**: Instead of $O(N^2)$, we only compare items that fall into the same hash bucket.
2. **Parallelization**: MinHash signatures can be computed independently for each document (e.g., using `multiprocessing` or Spark).
3. **Memory Mapping**: For extremely large signature matrices, use `numpy.memmap`.
"""

import numpy as np
from itertools import combinations
import os
import urllib.request
from pathlib import Path
from collections import defaultdict

class Config:
    TINY_SHAKESPEARE_URL = "https://huggingface.co/datasets/roneneldan/TinyStories/resolve/main/TinyStoriesV2-GPT4-train.txt"
    data_dir = "./data"

cfg = Config()

def download_tinystories(data_dir: str = "./data") -> str:
    os.makedirs(data_dir, exist_ok=True)
    dst = os.path.join(data_dir, "tinystories.txt")
    if not os.path.exists(dst):
        print(f" Downloading TinyStories -> {dst}")
        urllib.request.urlretrieve(cfg.TINY_SHAKESPEARE_URL, dst)
    return dst

def prepare_data():
    path = download_tinystories(cfg.data_dir)
    text = Path(path).read_text(encoding="utf-8")
    return text

class MinHashDeduplicator:
    def __init__(self, num_hashes=128, ngram_size=5, threshold=0.85):
        self.num_hashes = num_hashes
        self.ngram_size = ngram_size
        self.threshold = threshold
        self.a = np.random.randint(1, 2**32, size=num_hashes)
        self.b = np.random.randint(0, 2**32, size=num_hashes)
        self.p = 2**31 - 1

    def compute_minhash(self, text: str):
        tokens = text.lower().split()
        ngrams = set(tuple(tokens[i:i+self.ngram_size]) for i in range(len(tokens)-self.ngram_size+1))
        signature = np.full(self.num_hashes, np.inf)
        for ngram in ngrams:
            ngram_hash = hash(ngram) & 0xFFFFFFFF
            hashed = (self.a * ngram_hash + self.b) % self.p
            signature = np.minimum(signature, hashed)
        return signature.astype(np.uint32)

    def build_lsh_buckets(self, signatures: np.ndarray, n_bands: int = 16):
        n_docs, n_hashes = signatures.shape
        rows_per_band = n_hashes // n_bands
        buckets = defaultdict(list)
        for doc_id in range(n_docs):
            for band in range(n_bands):
                start, end = band * rows_per_band, (band+1) * rows_per_band
                band_sig = tuple(signatures[doc_id, start:end])
                buckets[hash((band, band_sig))].append(doc_id)
        return buckets

    def jaccard_from_signatures(self, sig1, sig2):
        return float((sig1 == sig2).mean())

def get_duplicates_scalable(docs, dedup, n_bands=20):
    print("Computing signatures...")
    signatures = np.array([dedup.compute_minhash(d) for d in docs])
    print("Bucketing documents...")
    buckets = dedup.build_lsh_buckets(signatures, n_bands=n_bands)
    potential_duplicates = set()
    for doc_ids in buckets.values():
        if len(doc_ids) > 1:
            for i, j in combinations(sorted(doc_ids), 2):
                potential_duplicates.add((i, j))
    print(f"Verifying {len(potential_duplicates)} candidate pairs...")
    real_duplicates = [(i, j) for i, j in potential_duplicates if dedup.jaccard_from_signatures(signatures[i], signatures[j]) >= dedup.threshold]
    return real_duplicates

# Execution logic
corpus_text = prepare_data()
docs = [p.strip() for p in corpus_text.split('<|endoftext|>') if len(p.strip()) > 50]
dedup = MinHashDeduplicator(num_hashes=128, threshold=0.8)
large_slice = docs[:1000] # Smaller slice for faster demo
duplicate_indices = get_duplicates_scalable(large_slice, dedup)
print(f"Found {len(duplicate_indices)} duplicates in {len(large_slice)} documents.")



"""### Character vs. Subword (Llama) Tokenization

| Feature | Character-level | Llama (Subword) |
| :--- | :--- | :--- |
| **Unit** | Individual characters (a, b, c) | Subword units (the, ing, tion) |
| **Vocab Size** | Very small (~256 for bytes) | Large (32,000 for Llama 1/2) |
| **Sequence Length** | Very long (1 token per char) | Short (approx. 0.75 words per token) |
| **Information Density** | Low | High |
"""

test_word = "Deduplication"

# Character level
char_tokens = list(test_word)

# Llama subword level
llama_tokens = tokenizer.tokenize(test_word)

print(f"Word: {test_word}")
print(f"Character tokens ({len(char_tokens)}): {char_tokens}")
print(f"Llama tokens ({len(llama_tokens)}): {llama_tokens}")

def heuristic_quality_filter(text_list):
    """Example filters used in pretraining (e.g., Gopher, LLaMA)."""
    filtered_docs = []
    for doc in text_list:
        # 1. Length filter (too short is often noise)
        if len(doc) < 100: continue

        # 2. Symbol-to-word ratio (prevents garbage/code-heavy snippets in natural language)
        words = doc.split()
        symbol_count = sum(1 for char in doc if not char.isalnum() and not char.isspace())
        if symbol_count / len(doc) > 0.1: continue

        filtered_docs.append(doc)
    return filtered_docs

cleaned_docs = heuristic_quality_filter(docs)
print(f"Docs remaining after quality filters: {len(cleaned_docs)}/{len(docs)}")

from transformers import AutoTokenizer
try:
    # Using a standard Llama-style tokenizer as an example
    tokenizer = AutoTokenizer.from_pretrained("hf-internal-testing/llama-tokenizer")

    # Tokenize the first cleaned doc
    sample_tokens = tokenizer.encode(cleaned_docs[0])
    print(f"Original Text (Start): {cleaned_docs[0][:50]}...")
    print(f"\nSample Tokenized IDs (first 10): {sample_tokens[:10]}")
    print(f"Vocabulary size: {tokenizer.vocab_size}")

    # Show decoding back to text
    print(f"\nDecoded back: {tokenizer.decode(sample_tokens[:10])}")
except Exception as e:
    print(f"Error: {e}")

# lets work on this ideas , first thing that came to my mind was to maybe try curriculum learning. It would look something like this :
#
# Fix everything (seed, model depth, token budget, eval interval).
# 2 Compare:
#
# Baseline random sampling
# Curriculum warmup (first 10-20% tokens) then baseline sampling
# I assume this would involve training a classifier first to score documents from Fineweb-Edu according to their "difficulty" (score categories could be 0-5).
# For this we can build a tiny subset of documents annotated by a LLM and train the classifier on it.

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.ensemble import RandomForestClassifier
import numpy as np

# 1. Simulate 'Educational Value' Labels (0-5)
annotated_data = [
    ("The Pythagorean theorem states that a^2 + b^2 = c^2 in a right triangle.", 5),
    ("Python is a high-level, interpreted programming language known for readability.", 4),
    ("Today I went to the store and bought some milk and bread.", 2),
    ("CLICK HERE FOR AMAZING DEALS AND FREE COUPONS!!!", 0),
    ("The mitochondria is the powerhouse of the cell.", 4),
    ("lol idk what to write here just testing stuff 123", 1)
]

texts, labels = zip(*annotated_data)
vectorizer = TfidfVectorizer(max_features=1000)
X = vectorizer.fit_transform(texts)

# Train a simple classifier
educational_scorer = RandomForestClassifier(n_estimators=50)
educational_scorer.fit(X, labels)

def get_educational_score(text):
    vec = vectorizer.transform([text])
    return int(educational_scorer.predict(vec)[0])

# Ensure cleaned_docs exists
if 'cleaned_docs' not in locals():
    # Fallback to creating docs if needed
    corpus_text = prepare_data()
    docs = [p.strip() for p in corpus_text.split('<|endoftext|>') if len(p.strip()) > 50]
    cleaned_docs = heuristic_quality_filter(docs)

# Score documents
scored_docs = []
print("Scoring documents for curriculum...")
for doc in cleaned_docs[:2000]:
    score = get_educational_score(doc)
    scored_docs.append({'text': doc, 'score': score})

print(f"Scoring complete. Sample scores: {[d['score'] for d in scored_docs[:10]]}")

import random

class CurriculumSampler:
    def __init__(self, scored_docs):
        self.docs = scored_docs
        # Group docs by score
        self.buckets = {i: [d['text'] for d in scored_docs if d['score'] == i] for i in range(6)}

    def sample_batch(self, size, step, total_steps, warmup_frac=0.2):
        warmup_steps = total_steps * warmup_frac

        if step < warmup_steps:
            # Curriculum phase: Favor higher scores (4-5)
            high_quality_pool = self.buckets[4] + self.buckets[5]
            if not high_quality_pool:
                high_quality_pool = [d['text'] for d in self.docs]
            return random.choices(high_quality_pool, k=size)
        else:
            # Baseline phase: Random sampling from everything
            return random.choices([d['text'] for d in self.docs], k=size)

# Initialize sampler
curr_sampler = CurriculumSampler(scored_docs)

# Test Sampler
print("Warmup Sample (Step 10):", curr_sampler.sample_batch(size=1, step=10, total_steps=100)[0][:100])
print("Baseline Sample (Step 50):", curr_sampler.sample_batch(size=1, step=50, total_steps=100)[0][:100])

"""the fundamental concepts and methodologies of cluster analysis, an unsupervised learning technique used to discover and separate hidden subsets in data.
Partitioning and Hierarchical Methods: Explores foundational algorithms like k-means and k-medoids.
Density and Grid-Based Methods: Details techniques that find clusters of arbitrary shapes based on the density of data (DBSCAN) or by partitioning the data space into a grid structure (STING).
Clustering Evaluation: Discusses methods for assessing clustering quality, determining the optimal number of clusters, and evaluating clustering tendency.
"""